esphome:
  name: solis
  friendly_name: solis

esp8266:
  #board: esp01_1m
  board: d1_mini

# Enable logging
logger:


uart:
  id: mod_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: D1
  id: modbus1
  send_wait_time: 200ms

modbus_controller:
  - id: solis
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    command_throttle: 200ms
    update_interval: 30s

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: modbus_controller
    modbus_controller_id: solis
    id: ac_watts
    name: "AC Watts"
    address: 3005
    unit_of_measurement: "W" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    register_count: 2
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: dc_1_voltage
    name: "DC1 Voltage"
    address: 3021
    unit_of_measurement: "V" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: dc_1_current
    name: "DC1 current"
    address: 3022
    unit_of_measurement: "A" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: dc_2_voltage
    name: "DC2 Voltage"
    address: 3023
    unit_of_measurement: "V" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: dc_2_current
    name: "DC2 current"
    address: 3024
    unit_of_measurement: "A" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: ac_voltage
    name: "AC Voltage"
    address: 3034
    unit_of_measurement: "V" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: ac_current
    name: "AC current"
    address: 3038
    unit_of_measurement: "A" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: ac_frequency
    name: "AC Frequency"
    address: 3042
    unit_of_measurement: "Hz" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: solis
    id: inverter_tempterature
    name: "Inverter Temperature"
    address: 3041
    unit_of_measurement: "°C" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: inverter_AlltimeEnergy_KW
    name: "Inverter AlltimeEnergy"
    address: 3009
    unit_of_measurement: "kWh" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    register_count: 2

    
  - platform: modbus_controller
    modbus_controller_id: solis
    id: today_KW
    name: "Generated Today"
    address: 3014
    unit_of_measurement: "kWh" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: yesterday_KW
    name: "Generated Yesterday"
    address: 3015
    unit_of_measurement: "kWh" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: solis
    id: month_KW
    name: "Generated This Month"
    address: 3011
    unit_of_measurement: "kWh" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    register_count: 2

  - platform: modbus_controller
    modbus_controller_id: solis
    id: year_KW
    name: "Generated This Year"
    address: 3017
    unit_of_measurement: "kWh" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    register_count: 2


# Enable Home Assistant API
api:
  encryption:
    key: "X9iwr4FGQ7Y5qdtvrSwiOliBKFhOEARdOzfUkFwIjYE="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Cd7B54"
    password: "6jrlzTAirwYe"

captive_portal:
    
    # Example configuration entry
web_server:
  port: 80